version: '3.8'

services:
  backend:
    container_name: surekha72-backend
    build: ./Backend
    ports:
      - "3037:3037"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=employee_portal

  employee-side:
    container_name: surekha72-employee-side
    build: ./Employee-side
    ports:
      - "8069:80"
    depends_on:
      - backend

  hr-view:
    container_name: surekha72-hr-view
    build: ./HR-view
    ports:
      - "8070:80"
    depends_on:
      - backend

  postgres:
    container_name: surekha72-postgres
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_portal
    volumes:
      - pgdata72:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata72:

